import type { Profile, Order, Session, DemandPost, Post, Notification, Transaction } from '@/types'

export const MOCK_USER: Profile = {
  id: 'user-1',
  username: 'arjun_sharma',
  full_name: 'Arjun Sharma',
  email: 'arjun@iit.ac.in',
  avatar_url: 'https://api.dicebear.com/8.x/notionists/svg?seed=arjun',
  bio: 'CS Engineering student @ IIT Madras. React enthusiast & ML hobbyist. Helping peers level up! 🚀',
  role: 'student',
  education_level: 'UG',
  institution: 'IIT Madras',
  city: 'Chennai',
  state: 'Tamil Nadu',
  personality_type: 'extrovert',
  xp: 2840,
  level: 5,
  reputation_score: 4.8,
  trust_score: 4.9,
  study_streak: 12,
  is_verified: true,
  is_premium: true,
  women_safe_mode: false,
  anonymous_mode: false,
  email_notifications: true,
  push_notifications: true,
  total_orders: 24,
  completed_orders: 21,
  total_earnings: 18500,
  total_spent: 7200,
  rating: 4.8,
  review_count: 19,
  followers_count: 142,
  following_count: 67,
  created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
}

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1',
    order_number: 'SG-2024-001234',
    buyer_id: 'user-1',
    seller_id: 'user-2',
    title: 'Physics Thermodynamics Assignment - 5 Pages',
    description: 'Need comprehensive coverage of Carnot cycle and heat engines',
    category: 'writing',
    status: 'in_progress',
    education_level: 'UG',
    subject: 'Physics',
    topic: 'Thermodynamics',
    page_count: 5,
    base_price: 15,
    urgency_multiplier: 1.35,
    platform_commission: 5.06,
    seller_amount: 15.19,
    total_price: 20.25,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    delivery_days: 2,
    payment_status: 'escrow',
    attachments: [],
    revision_count: 0,
    max_revisions: 2,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    delivery_mode: 'online',
  },
  {
    id: 'ord-2',
    order_number: 'SG-2024-001189',
    buyer_id: 'user-1',
    seller_id: 'user-3',
    title: 'React + Node.js Full Stack Web Dev Project',
    description: 'E-commerce platform with payment integration',
    category: 'project',
    status: 'review',
    education_level: 'UG',
    subject: 'Computer Science',
    topic: 'Web Development',
    project_type: 'web_dev',
    complexity: 'advanced',
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    base_price: 5500,
    urgency_multiplier: 1.0,
    platform_commission: 1375,
    seller_amount: 4125,
    total_price: 5500,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    delivery_days: 14,
    payment_status: 'escrow',
    attachments: [],
    revision_count: 1,
    max_revisions: 3,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    delivery_mode: 'online',
  },
  {
    id: 'ord-3',
    order_number: 'SG-2024-001050',
    buyer_id: 'user-1',
    seller_id: 'user-4',
    title: 'Calculus Weekly Tutoring - 4 Sessions',
    description: 'Integration techniques and differential equations',
    category: 'tutor',
    status: 'completed',
    education_level: 'UG',
    subject: 'Mathematics',
    topic: 'Calculus',
    weekly_sessions: 4,
    base_price: 3200,
    urgency_multiplier: 1.0,
    platform_commission: 800,
    seller_amount: 2400,
    total_price: 3200,
    payment_status: 'released',
    attachments: [],
    revision_count: 0,
    max_revisions: 0,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    delivery_mode: 'online',
  },
]

export const MOCK_SESSIONS: Session[] = [
  {
    id: 'sess-1',
    tutor_id: 'user-4',
    student_id: 'user-1',
    title: 'Calculus - Integration by Parts',
    subject: 'Mathematics',
    topic: 'Integration',
    status: 'scheduled',
    delivery_mode: 'online',
    scheduled_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 60,
    student_attended: false,
    tutor_attended: false,
    meet_link: 'https://meet.google.com/abc-defg-hij',
    price: 800,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sess-2',
    tutor_id: 'user-5',
    student_id: 'user-1',
    title: 'React Hooks Deep Dive',
    subject: 'Computer Science',
    topic: 'React Hooks',
    status: 'completed',
    delivery_mode: 'online',
    scheduled_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 90,
    student_attended: true,
    tutor_attended: true,
    student_rating: 5,
    student_review: 'Excellent session! Very clear explanations.',
    price: 1200,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_DEMAND_POSTS: DemandPost[] = [
  {
    id: 'dp-1',
    user_id: 'user-6',
    title: 'Need help in Physics - Thermodynamics',
    description: 'Struggling with Carnot cycle problems. Need someone to explain heat engines and efficiency calculations with practice problems.',
    category: 'student_tutor',
    subject: 'Physics',
    topic: 'Thermodynamics',
    education_level: 'UG',
    budget_min: 150,
    budget_max: 300,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_urgent: true,
    is_open: true,
    views: 47,
    proposals_count: 5,
    tags: ['physics', 'thermodynamics', 'urgent'],
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dp-2',
    user_id: 'user-7',
    title: 'AI/ML Mini Project - Sentiment Analysis',
    description: 'Need a complete sentiment analysis project using BERT or similar transformer model. Must include training pipeline, evaluation, and demo.',
    category: 'project',
    subject: 'Computer Science',
    topic: 'AI/ML',
    education_level: 'UG',
    budget_min: 2000,
    budget_max: 4000,
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    is_urgent: false,
    is_open: true,
    views: 128,
    proposals_count: 12,
    tags: ['ai', 'ml', 'python', 'nlp', 'bert'],
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dp-3',
    user_id: 'user-8',
    title: 'React + TypeScript Tutoring - 4 Sessions',
    description: 'Learning React with TypeScript. Need experienced mentor to cover hooks, state management with Zustand, and Next.js basics.',
    category: 'tutor',
    subject: 'Computer Science',
    topic: 'React',
    education_level: 'UG',
    budget_min: 2000,
    budget_max: 3500,
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_urgent: false,
    is_open: true,
    views: 89,
    proposals_count: 8,
    tags: ['react', 'typescript', 'nextjs', 'tutoring'],
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'dp-4',
    user_id: 'user-9',
    title: 'Organic Chemistry Assignment - Reaction Mechanisms',
    description: '10 problems on nucleophilic substitution, elimination reactions, and aromatic chemistry. Need detailed solutions with mechanisms.',
    category: 'writing',
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    education_level: '12th',
    budget_min: 300,
    budget_max: 600,
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    is_urgent: true,
    is_open: true,
    views: 63,
    proposals_count: 3,
    tags: ['chemistry', 'organic', 'urgent', 'assignment'],
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'user-1',
    type: 'order',
    title: 'Order Update',
    message: 'Your physics assignment is 80% complete. Delivery tomorrow!',
    link: '/orders/ord-1',
    is_read: false,
    metadata: {},
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'user-1',
    type: 'session',
    title: 'Session Starting Soon',
    message: 'Your Calculus session starts in 2 hours. Click to join.',
    link: '/sessions',
    is_read: false,
    metadata: {},
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'user-1',
    type: 'achievement',
    title: '🔥 Study Streak!',
    message: 'Amazing! You\'re on a 12-day study streak. Keep it up!',
    is_read: false,
    metadata: {},
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    user_id: 'user-1',
    type: 'payment',
    title: 'Payment Received',
    message: '₹2,400 has been released to your wallet from Order SG-2024-001050.',
    link: '/wallet',
    is_read: true,
    metadata: {},
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-5',
    user_id: 'user-1',
    type: 'social',
    title: 'New Follower',
    message: 'Priya Menon started following you.',
    link: '/profile/priya_menon',
    is_read: true,
    metadata: {},
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-1',
    wallet_id: 'w-1',
    user_id: 'user-1',
    type: 'escrow_release',
    amount: 2400,
    balance_after: 5200,
    description: 'Payment released - Calculus Tutoring (SG-2024-001050)',
    payment_method: 'escrow',
    status: 'released',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'txn-2',
    wallet_id: 'w-1',
    user_id: 'user-1',
    type: 'debit',
    amount: 20.25,
    balance_after: 5179.75,
    description: 'Order payment - Physics Assignment (SG-2024-001234)',
    payment_method: 'UPI',
    status: 'escrow',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'txn-3',
    wallet_id: 'w-1',
    user_id: 'user-1',
    type: 'credit',
    amount: 1800,
    balance_after: 3380,
    description: 'Earnings - React Tutorial Session',
    payment_method: 'platform',
    status: 'released',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    user_id: 'user-1',
    content: '🚀 Just completed my first AI/ML project! Built a sentiment analysis model using BERT with 94% accuracy on movie reviews. The fine-tuning process was challenging but so rewarding. Happy to help anyone starting with transformers! #MachineLearning #Python #NLP',
    post_type: 'achievement',
    image_urls: [],
    tags: ['ml', 'python', 'nlp', 'bert'],
    subject: 'Computer Science',
    likes_count: 47,
    comments_count: 12,
    saves_count: 23,
    shares_count: 8,
    views: 312,
    is_pinned: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    liked: false,
    saved: false,
  },
  {
    id: 'post-2',
    user_id: 'user-10',
    content: '❓ DOUBT: Can anyone explain why SN2 reactions don\'t work well with tertiary substrates? I understand steric hindrance prevents backside attack, but my professor mentioned there\'s another factor related to charge stability. Any help appreciated! 🙏',
    post_type: 'doubt',
    image_urls: [],
    tags: ['chemistry', 'organic', 'doubt'],
    subject: 'Chemistry',
    likes_count: 15,
    comments_count: 8,
    saves_count: 5,
    shares_count: 2,
    views: 89,
    is_pinned: false,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    liked: true,
    saved: false,
  },
]

export const TOP_SKILLS = [
  { category: 'writing', user: 'Priya Menon', rating: 4.9, orders: 78, price: '₹3/page', subject: 'English Literature' },
  { category: 'tutor', user: 'Rahul Verma', rating: 4.8, orders: 124, price: '₹800/session', subject: 'Mathematics' },
  { category: 'project', user: 'Ananya Kumar', rating: 5.0, orders: 45, price: '₹2500+', subject: 'Web Development' },
  { category: 'student_tutor', user: 'Karthik S', rating: 4.7, orders: 56, price: '₹200/session', subject: 'Physics' },
  { category: 'companion', user: 'Meera Raj', rating: 4.9, orders: 34, price: '₹150/week', subject: 'General Study' },
  { category: 'craft', user: 'Deepak Nair', rating: 4.6, orders: 29, price: '₹500+', subject: 'Science Models' },
]
